sudo pip3 install django --upgrade
sudo pip3 install gunicorn --upgrade
sed -i -e 's/\/usr\/bin\/python/\/usr\/bin\/python3/' \usr\sbin\gunicorn-debian
sed -i -e 's/\/usr\/bin\/python/\/usr\/bin\/python3/' \usr\bin\gunicorn
sed -i -e 's/17.5/19.9.0/' \usr\bin\gunicorn
sed -i -e 's/\/usr\/bin\/python/\/usr\/bin\/python3/' \usr\bin\gunicorn_django
sed -i -e 's/17.5/19.9.0/' \usr\bin\gunicorn_django
sed -i -e 's/\/usr\/bin\/python/\/usr\/bin\/python3/' \usr\bin\gunicorn_paster
sed -i -e 's/17.5/19.9.0/' \usr\bin\gunicorn_paster
